spring.datasource.url: jdbc:h2:file:./camunda1-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo
#
#spring:
#  datasource:
#    username: bamunda_bpm_testing
#    password: 123456
#    url: jdbc:oracle:thin:@192.168.2.24:1521:orcl
#    driver-class-name: oracle.jdbc.OracleDriver
#  jpa:
#    hibernate:
#      dialect: org.hibernate.dialect.Oracle12cDialect
#      ddl-auto: none

myCamunda:
  dataSource:
    username: sa
    password: ''
    url: jdbc:h2:file:./camunda2-h2-database
    driverClassName: org.h2.Driver